### ISSUE TITLE
Module crashes on ParseError

### ISSUE THREAD

**Issue by david-hoffman** [blink1073/tifffile#8]
Perhaps this is an intended effect, but if the xml in the tif header is incorrect the module will fail to load the data and will raise a `ParseError`. See example below.

``` python
>>> from skimage.external import tifffile as tif
>>> tif.imread('testtif.tif')
  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 44, column 19
```

One can work around this by creating a TiffFile object and reading in the pages one by one:

``` python
>>> with tif.TiffFile('testtif.tif') as mytif:
...    data = np.array([ page.asarray() for page in mytif.pages])
```

**Comment by blink1073** [comment]
Thanks for reporting @david-hoffman.  
Does the following work for your image?:

```python
with open('testtif.tif', 'rb') as f:
        tif = TiffFile(f)
        data = tif.asarray(**kwargs)
```

**Comment by david-hoffman** [comment]
Nope, same error.

**Comment by blink1073** [comment]
Okay, I'll make a PR that uses your incantation in our `pil` and `tifffile` plugins.

**Comment by blink1073** [comment]
Looking at it again, I don't think we want to give up the facilities that `asarray` provides.  In your case, you'd have to fix your files by manually saving them with `tifffile` and then loading them.

**Comment by cgohlke** [comment]
Please send me the file.

**Comment by david-hoffman** [comment]
The file is too big to send (> 50 MB) but I’ve attached the XML.

**Comment by cgohlke** [comment]
Thank you. The XML claims to be UTF-8 encoded but contains two characters that are not valid UTF-8. Probably the software that generated the TIFF file forgot to encode a latin-1 or similar encoded string before writing it to disk. Or the software you used to extract the XML got it wrong. Anyway, I believe this will be fixed in the next version of tifffile.py, which decodes the xml ignoring errors.
